### ISSUE TITLE
Getting strange error: 28s › Serverless › There's a problem with your files and they could not be loaded by this Component.  Original error: Response code 403 (Forbidden)  

### ISSUE THREAD

**Issue by bugb** [serverless/components#1006]
# Description

I can not use serverless to deploy.

## Additional Data

```yml
name: myapp
org: myorg
inputs: # The configuration the Component accepts
  src:
    src: ./src
    hook: npm run build
    dist: ./dist
  domain: mydomain
```

I have set AWS as my default provider but I can not make it works.

Getting strange error:
```
28s › Serverless › There's a problem with your files and they could not be loaded by this Component.  Original error: Response code 403 (Forbidden)  
```
