### ISSUE TITLE
How to run a different hook command for each stage?

### ISSUE THREAD

**Issue by Lobosque** [serverless/components#1024]
# Description
I want to run different build commands for my static website, depending on the stage.
The following does not work, because the `${stage}` is empty, even when explicitly setting the stage via the `--stage` cli parameter:
```
org: lobosque
app: foo-frontend
name: vue-starter
component: website

inputs:
  domain: ${param:domain}
  src:
    src: ./src
    hook: npm run build-${stage}
    dist: ./dist
```
