### ISSUE TITLE
Syntax Conventions Should Be Stated Clearly

### ISSUE THREAD

**Issue by ac360** [serverless/components#15]
Making sure everyone understand component syntax conventions will help collaboration.

Suggestion: List these in the README, like this:

**Configuration**

Use camel-case, even for acronyms.

Example:
```yml
inputs:
  name:
  endpointUrl: 
```

**Component Types**

Use lowercase with hyphens

Example:
```yml
type: aws-api-gateway
```

**Component Aliases**

Use camel-case, even for acronyms.

Example:
```yml
components:
  myApi:
    type: aws-api-gateway
```
