### ISSUE TITLE
Add an aws-sns-topic component

### ISSUE THREAD

**Issue by brianneisler** [serverless/components#174]
# Description

Implement a basic `aws-sns-topic` component. 

## Inputs
- `name: string`
- `displayName:string (optional)` (set using setTopicAttributes https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SNS.html#setTopicAttributes-property)
- `policy: JSON | AWSTopicPolicyDocument`  (set using setTopicAttributes)
- `deliveryPolicy: SNSDeliveryPolicy` (set using setTopicAttributes)

## Outputs
- `arn: string`

## Types

SNSDeliveryPolicy 
example pulled from here https://docs.aws.amazon.com/sns/latest/api/API_SetTopicAttributes.html
```
{ 
  "http": {
    "defaultHealthyRetryPolicy": { 
       "minDelayTarget": <int>,
       "maxDelayTarget": <int>,
       "numRetries": <int>, 
       "numMaxDelayRetries": <int>, 
       "backoffFunction": "<linear|arithmetic|geometric|exponential>" 
    }, 
    "disableSubscriptionOverrides": <boolean>, 
    "defaultThrottlePolicy": { 
      "maxReceivesPerSecond": <int> 
    }
  } 
}
```

AWSTopicPolicyDocument
- TODO: need to figure out what this looks like

## Requirements
- [ ] tests
- [ ] documentation
- [ ] examples

**Comment by brianneisler** [comment]
Hey @laardee, the best example i could find of what the AWSTopicPolicyDocument should look like is in the CloudFormation docs located here 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-iam.html#scenario-sns-policy

It would probably be good to support a general js object and string JSON

I also realized that there's a handful of other attributes that can be set that aren't very well documented around message status topics

https://docs.aws.amazon.com/sns/latest/dg/msg-status-topics.html
https://www.terraform.io/docs/providers/aws/r/sns_topic.html#policy

We could probably punt on support for those but something to be aware of.

**Comment by laardee** [comment]
Thanks @brianneisler , the AWSTopicPolicyDocument was straightforward to implement. As the policy can be anything, I don't think there should be much "magic" when defining it, just the policy as an object or a JSON string that is then applied.

Not entirely related to this, but is there a way (or in the roadmap) to refer to the variables saved to the state? For example, if I want to use the topic ARN in the inline policy, which I know is available in the state before creating the policy.

```yaml
components:
  snsTopic:
    type: aws-sns-topic
    inputs:
      name: my-sns-topic
      displayName: MySNSTopic
      policy:
        Version: '2008-10-17'
        Id: policy_id
        Statement:
        - Effect: Allow
          ....
          Resource: ${state.topicArn} <--- something like this
          ....
```

---

Then the extra attributes, it is kind of funny that the AWS SDK documentation doesn't say anything about these in the `setTopicAttributes` which is used to set these, it states that the valid values are `Policy | DisplayName | DeliveryPolicy`. Anyways, I was thinking of structuring the delivery status attributes to an array to avoid noise in the root level of the component:

```yaml
components:
  snsTopic:
    type: aws-sns-topic
    inputs:
      name: my-sns-topic
      displayName: MySNSTopic
      deliveryStatusAttributes:
        - ApplicationSuccessFeedbackRoleArn: ${snsSuccessRole.arn}
          ApplicationSuccessFeedbackSampleRate: 100
          ApplicationFailureFeedbackRoleArn: ${snsFailureRole.arn}
        - HTTPSuccessFeedbackRoleArn: ${snsSuccessRole.arn}
          HTTPSuccessFeedbackSampleRate: 100
          HTTPFailureFeedbackRoleArn: ${snsFailureRole.arn}
        - LambdaSuccessFeedbackRoleArn: ${snsSuccessRole.arn}
          LambdaSuccessFeedbackSampleRate: 100
          LambdaFailureFeedbackRoleArn: ${snsFailureRole.arn}
        - SQSSuccessFeedbackRoleArn: ${snsSuccessRole.arn}
          SQSSuccessFeedbackSampleRate: 100
          SQSFailureFeedbackRoleArn: ${snsFailureRole.arn}
```

Where the `snsSuccessRole` and `snsFailureRole` are created as separate components.

The AWS web console is hardly a good source for the ux reference, but this way the component root would be similar to "Actions" menu in SNS topic view.

But now I'm facing an issue with the deployment. It seems that there is some (undocumented?) rate limit with `setTopicAttributes`. If I make call parallel, it writes only one or two delivery attributes (left-hand side of the capture), but sequentially, everything goes smoothly (right-hand side of the capture). The weird thing is that I don't get any error that the rate is exceeding, or request fails, it just silently fails.

![sns-delivery-fail](https://user-images.githubusercontent.com/4726921/40276590-bc8b4ea8-5c16-11e8-96c8-3c52a12a06b3.png)

Maybe it is better to refactor the code that updates the topic attributes to run sequentially, but it would be nice to know the rate limit if the sequential requests can exceed the limit...
