### ISSUE TITLE
Add aws-cloudwatch-metric-alarm component

### ISSUE THREAD

**Issue by brianneisler** [serverless/components#179]
# Description

Add an `aws-cloudwatch-metric-alarm` component for setting up an AWS CloudWatch metric alarm.

### Inputs
- `name: string`
- `description: string`

- `actionsEnabled: boolean`
- `okActions: Array<string>`
- `alarmActions: Array<string>`
- `insufficientDataActions: Array<string>`
- `metricName: string`
- `namespace: string`
- `statistic: string`
- `extendedStatistic: string`
- `dimensions: Array<{name: string (min:1, max: 255), value: string (min:1, max: 255)}>`
- `period: int (10, 30, 60*x, max: 86400)`
- `unit: enum`
"Seconds"
"Microseconds"
"Milliseconds"
"Bytes"
"Kilobytes"
"Megabytes"
"Gigabytes"
"Terabytes"
"Bits"
"Kilobits"
"Megabits"
"Gigabits"
"Terabits"
"Percent"
"Count"
"Bytes/Second"
"Kilobytes/Second"
"Megabytes/Second"
"Gigabytes/Second"
"Terabytes/Second"
"Bits/Second"
"Kilobits/Second"
"Megabits/Second"
"Gigabits/Second"
"Terabits/Second"
"Count/Second"
"None"
- `evaluationPeriods: int`
- `datapointsToAlarm: int`
- `threshold: float`
- `comparisonOperator: enum`
"GreaterThanOrEqualToThreshold"
"GreaterThanThreshold"
"LessThanThreshold"
"LessThanOrEqualToThreshold"
- `treatMissingData: enum (breaching, notBreaching, ignore, missing)`
- `evaluateLowSampleCountPercentile: enum (evaluate, ignore)`

### Outputs
- `name: string`

Requirements
- [ ] tests
- [ ] documentation
- [ ] examples

**Comment by tmclaugh** [comment]
This component is important. If I'm building infrastructure, I don't want people in my organization using AWS components directly.  I want them to be using higher level components with patterns that we've blessed for reliable operation.

For example, don't use aws-sqs-queue directly. Do use myorg-aws-sqs which includes a queue and aws-cloudwatch-metric-alarm components.  This is letting an organization repeat the same successful patterns that were doable with Puppet and Chef, even Terraform.

**Comment by Vadorequest** [comment]
Totally supporting this, I'm trying to do it by hand and failing miserably so far. It's quite complicated to get started with.

I wanted to setup a `AWS::Route53::HealthCheck` which is easy, but configuring a `AWS::CloudWatch::Alarm` to get notifications when something goes wrong is another level entirely.

I tried something following those docs:

- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html#cfn-cloudwatch-alarms-evaluationperiods
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-cloudwatch.html

And I'm currently ending up with this (not working for the Alarm resource)

> I'm not looking for help, just wanna show how complicated it gets to make a point about the usefulness of making in into a documented component.

```yaml
resources:
  Resources:
    healthCheckAlarm:
      Type: "AWS::CloudWatch::Alarm"
      Properties:
        ActionsEnabled: true
        AlarmActions:
          - Send message to topic "email-it-support" (it@studylink.fr) # Not sure if that's the right format, doubt so
        AlarmDescription: Alarm for ${self:custom.stages.${self:provider.stage}.domain.name}
        AlarmName: HealthCheckAlarm-${self:custom.stages.${self:provider.stage}.domain.name}
        ComparisonOperator: LowerThanThreshold # No list of possible values in doc...
        EvaluateLowSampleCountPercentile: evaluate # No list of possible values in doc...
        MetricName: HealthCheckStatus
        Namespace: AWS/Route53
        Period: '21600' # Don't know what this is supposed to be, millisecond or second? Doc doesn't say clearly
        Statistic: Minimum # No list of possible values in doc...
        TreatMissingData: missing # No list of possible values in doc...
#        Unit: String
        EvaluationPeriods: '1'
#        Threshold: # No idea how to configure this, are we supposed to create the Notification using SLS as well? Gets quite complicated... (lack of guidance in AWS docs)
#          Ref: "AlarmThreshold"
#        ComparisonOperator: GreaterThanThreshold
#        AlarmActions:
#        - Ref: "BillingAlarmNotification"
#        InsufficientDataActions:
#        - Ref: "BillingAlarmNotification"
    healthCheck: # This works fine, except for the AlarmIdentifier thing
      Type: "AWS::Route53::HealthCheck"
      Properties:
        HealthCheckConfig:
          AlarmIdentifier: # XXX Must be configured through AWS dashboard (mismatch with regions...)
            Name: HealthCheckAlarm-${self:custom.stages.${self:provider.stage}.domain.name}
            Region: us-east-1
          EnableSNI: true
          FailureThreshold: "3"
          FullyQualifiedDomainName: ${self:custom.stages.${self:provider.stage}.domain.name}
          MeasureLatency: true
          Port: "80"
#          Regions: # XXX Do not specify regions, use all regions by default
          RequestInterval: "30"
          Type: "HTTPS"
        HealthCheckTags:
          -
            Key: "env"
            Value: ${self:custom.environment}

```
