### ISSUE TITLE
aws-lambda runtime

### ISSUE THREAD

**Issue by ebisbe** [serverless/components#208]
Runtime is always node6

```
flickrPhotosFunction:
    type: aws-lambda
    inputs:
      name: enricbgFlickrPhotos
      runtime: nodejs8.10
      memory: 512
      timeout: 10
      handler: code/photos.handler
``` 
Despite running `components deploy` the runtime at my lambdas is always the older version of node ( v6 ). I have to set it manual in my aws console. After each deploy it resets to v6
