### ISSUE TITLE
rest-api: Deploying multiple http verbs for the same route deploys only the last verb

### ISSUE THREAD

**Issue by ebisbe** [serverless/components#209]
Deploying multiple http verbs for the same route deploys only the last verb. In the example below will only be available the GET /products.
Taken from the example https://serverless.com/blog/how-create-rest-api-serverless-components/

```
# ... snip

components:
  # ...snip
  productsApi:
    type: rest-api
    inputs:
      gateway: aws-apigateway
      routes:
        /products:
          post:
            function: ${createProduct}
            cors: true
          get:
            function: ${listProducts}
            cors: true         
```
