### ISSUE TITLE
Custom typing system

### ISSUE THREAD

**Issue by brianneisler** [serverless/components#211]
# Description

There are cases where we need to support custom types and custom validation rules for types.

raml-validate supports specifying custom types as well as specifying custom rules https://github.com/mulesoft-labs/node-raml-validate

However, it might make sense to change out this library for a more robust on like this https://www.npmjs.com/package/raml-typesystem

We should add support for setting up custom types in yaml. This work is based off the RAML types spec https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#raml-data-types

Example
```yml
type: my-component

inputTypes:
  foo:
    type: Foo
    default:
      bar: 123

types:
  Foo:
    type: object
    properties:
      bar: string 
```
