### ISSUE TITLE
Independently settable outputs

### ISSUE THREAD

**Issue by brianneisler** [serverless/components#212]
# Description
Having outputs returned by every function in a component hasn't turned out to be the best implementation.

Outputs need to be persisted across calls to different functions, settable by any function, but not required to return outputs.

Instead, we should introduce a function called `setOutputs` for setting the outputs. This method should accept an object similar to `saveState`

## Requirements

- Persist outputs in state across calls
- set outputs at the start when the state is loaded and the components are instantiated
- update the outputs when setOutputs is called
- setOutputs should merge the given object with the existing outputs
- setOutputs should return the context for chaining
## Example
```
type: my-component
outputTypes:
  foo:
    type: string
    description: foo output
  bar:
    type: string
    description: bar output
```
```
async function deploy(inputs, context) {
  doSomething()
  context = context.setOutputs({
    foo: 'abc'
  })

  doSomethingElse()
  context = context.setOutputs({
    bar: 'def'
  })

  // no longer support returning outputs.
}
```
