### ISSUE TITLE
Input type aliases

### ISSUE THREAD

**Issue by brianneisler** [serverless/components#217]
# Description

It would be convenient to be able to have alternate names for inputs that are aliases of the primary name.

```
type: aws-s3-bucket

inputTypes:
  bucket:
    type: string
    alias: 
      - 'name'
```

Which could be used like this...

```
type: my-component

components:
  myBucket:
    type: aws-s3-bucket
    inputs
      bucket:  my-bucket
```

or like this...

```
type: my-component

components:
  myBucket:
    type: aws-s3-bucket
    inputs
      name:  my-bucket
```

this would then show up in the inputs under the primary input name

```
const deploy = (inputs, context) => {
  console.log(inputs) // { bucket: 'my-bucket' }
}
```
