### ISSUE TITLE
AWS Components - Add credentials as inputs

### ISSUE THREAD

**Issue by ac360** [serverless/components#222]
Currently, the AWS Components do not have credentials as input types.  They depend on the user to have AWS credentials as environment variables or the user to have their credentials stored locally in the root of their machine.

Enabling passing in credentials makes it explicit which credentials the component is using, which is especially helpful in a situation where the component has AWS components as children.  It also enables components within the same project to be deployed to different AWS accounts.

Would love to see AWS credentials inputs on all AWS components as non-required input types.

**Comment by tommedema** [comment]
Since component inputs are in plain text, do you plan to put your credentials in plain text too? And version control that?

Credentials are typically left outside of source code for this exact reason. I would rather see a configuration option that would allow you to require certain environment variables, to make it explicit that credentials are expected through env.

**Comment by brianneisler** [comment]
We intend to do this with the new provider type. https://github.com/serverless/components/pull/260

An example of using a provider with the current components implementation would look like this
```yaml
type: MyService

components: 
  awsProvider: 
    type: AWSProvider
    inputs: 
      accessKeyId: ${env.AWS_ACCESS_KEY_ID} or encrypted text
      secretAccessKey: ${env.SECRET_ACCESS_KEY} or encrypted text
  awsLambdaFunction:
    type: AWSLambdaFunction
    inputs:
      provider: ${awsProvider}
      handler: ./handler.js
      ...
```

Currently, how the credentials get into the provider inputs is up to the end user. However, I do think it would make sense to introduce a new type for inputs. Something along the lines of "SensitiveString" which prevents the user from supply clear text and instead requires that the input be either a reference to another component property, an env value, or an encrypted string.
