### ISSUE TITLE
Move version declarations out of component type property

### ISSUE THREAD

**Issue by brianneisler** [serverless/components#228]
## Problem

Our current approach to version declarations has been to add them inline to the component usage like this...
```
components:
  myComponent:
     type: some-component@1.0.0
```

This has a number of issues associated with it.

1) Versions suddenly need to be managed in multiple places when using the same component multiple times and it becomes very easy to make a version mistake.

Example
```
components:
  foo1:
     type: foo@1.0.0
  foo2:
    type: foo@1.0.0
  foo3: 
    type: foo@1.0.0
```

If i upgrade the component, it's possible to make a mistake and accidentally miss one of the component versions

Example
```
components:
  foo1:
     type: foo@1.1.0
  foo2:
    type: foo@1.1.0
  foo3: 
    type: foo@1.0.0   # whoops, forgot to update this
```

2) If i'm using components programmatically within the component, I have no mechanism for statically declaring which components i'm using within the component. This means that component cannot programmatically download the necessary dependencies ahead of time, they actually have to download at runtime which is suboptimal.

Example
```
// index.js
function deploy(inputs, context) {
  const foo = context.load('foo@1.0.0', inputs)  // no way to discover this without running the actual code
}
```

## Solution
This all results in a situation where it dependency and version management is more difficult than it should be.

My suggestions for fixing this is to separately declare component dependencies from their actual usage.

```
type: my-component

dependencies:
  foo: ^1.0.0

components:
  myFoo:
    type: foo # this uses the version supplied in the dependencies above
```

This also gives us a mechanism for declaring components that are used programmatically

```
type: my-component

dependencies:
  bar: ^1.0.0 

# no declaration of components property
```

```
// index.js
function deploy(inputs, context) {
  const bar = context.load('bar', inputs)  // uses the version declared in serverless.yml dependencies
}

**Comment by jrmacks** [comment]
Excellent explanation of the problem and agree with your approach. One scenario to consider is if in one of your components you explicitly want to reference a different version. Perhaps it may be good to keep the current logic in place as an override to the root dependencies block? 

Example: 

```
type: my-component

dependencies:
  foo: ^1.0.0 

components:
  foo1:
    type: foo # uses root v1.0.0
  foo2:
    type: foo@1.1.0  # overriding the root dependency version
```
