### ISSUE TITLE
Deployment with circleci, CNAME already exists

### ISSUE THREAD

**Issue by ptrhck** [serverless/components#393]
I really like the serverless component idea. In particular, I would like to publish a static website using circleci.

However, if I update my code and want to redeploy using components, I get the following error:

`CNAMEAlreadyExists: One or more of the CNAMEs you provided are already associated with a different resource.`  
Nevertheless, it still uploads the files to S3. I assume there is some caching happening such that the serverless framework can associate the current deployment to a previous one. This is not available, as circleci fires up a new container. Is that right? Where can I find that folder such that I can save the cache?

Same holds true for the remove command, as the resources are not removed.

See my circleci config:

```
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/my-spa

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Serverless components and gatsby
          command: |
            sudo yarn global add gatsby-cli serverless-components
            yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Generate static website
          command: gatsby build

      - run:
          name: Deploy static website to AWS
          command: components remove
```
It should be noted, that I have set values for hostingDomain and aliasDomain even tough I have not registered the domains. The reason is, that I get another error if I do not specify input values as metioned in https://github.com/serverless/components/issues/299
