### ISSUE TITLE
Fix dual name problem

### ISSUE THREAD

**Issue by ac360** [serverless/components#419]
Currently, we use 1 naming convention for Components on NPM and 1 convention for components on Github.

Let's find a way to only use one name.

**Comment by eahefnawy** [comment]
How about this?

### latest version
```
myChatApp:
    component: @serverless/chat-app
    inputs:
      name: my-chat-app
```

### specific version
```
myChatApp:
    component: @serverless/chat-app@0.1.3
    inputs:
      name: my-chat-app
```

### semantic versioning
```
myChatApp:
    component: @serverless/chat-app@^0.1.0
    inputs:
      name: my-chat-app
```

those are all valid npm package name@version pairs. So all versioning stuff is handled by npm. In the background, we'd just run `npm pack name@version` into a global cache.
