### ISSUE TITLE
Declarative Component should be able to reference npm packages on the file system

### ISSUE THREAD

**Issue by ac360** [serverless/components#424]
like this:

```
name: my-project

myDNS:
  component: "../cloudflare-dns" 
  inputs:
      zone: about.me
```
