### ISSUE TITLE
Component: AWS API Gateway Endpoint Component

### ISSUE THREAD

**Issue by ac360** [serverless/components#431]
This Component does not create a whole REST API.  All it does is add/manage an endpoint to an existing REST API.

The goal of this Component is to adjust API endpoints without modifying the whole API.  The scope of this Component should only to add a single endpoint. 

You must pass in an API Gateway REST API ID or it will not work.  Therefore, the REST API must already be created.

This solves the problem of microservice components needing to use a whole API Gateway Component.  A microservice should never control the whole REST API.  It should only be able to add an endpoint to an existing one.

This Component should also track it's endpoint.  IF the endpoint path/method/config is changed, it must first remove that old endpoint, then add the new one.

It should also first check to see if the endpoint path/method exists already.  If it does exist, and this Component DID NOT create it, it should throw an error saying that endpoint is already taken.  The goal here is to not mess up existing API Endpoints that belong to others.

Overall, this Component when used within a Microservice Component would help developers work autonomously on a shared API Gateway REST API without conflicting and colliding.

**Comment by eahefnawy** [comment]
when you say REST API component, I'm guessing you mean `aws-api-gateway`? or that's another one?

Also does the endpoint component let the use define method/function mapping? or just creates an endpoint with `ANY` method and route all methods to a single function like we're doing with mono?

something like this?

```yml
usersEndpoint:
    component: "@serverless/endpoint"
    inputs:
        api: ${comp:restApi.id} # or any rest api id on their account
        /users:
             get: ${comp:getUsersFunction.arn} # or any rest api id on their account
             post: ${comp:createUsersFunction.arn} # or any rest api id on their account
```
