### ISSUE TITLE
Composable Primitives

### ISSUE THREAD

**Issue by ac360** [serverless/components#449]
This is a proposal to build some high-level primitive abstractions for common parts of the serverless architecture.

* Code
* Website
* Function
* REST API
* Queue
* PubSub

**The goals of these are as follows:**

* These primitives should be designed to compose together well, where it makes sense (e.g. the "Function" should work well with "REST API" and "Queue"), programmatically and declaratively (YAML).

* Each one of these should be able to work with multiple vendors over time, but not immediately.

* Each should feature standard configuration and custom configuration for vendor-specific features and quirks.

### Code

This takes code in any language and runs any necessary build process with it.

### Function

This is a Component for deploying code onto any FaaS provider.  

* This uses the "Code" Component behind the scenes to build code.

### REST API

This is a Component for deploying REST APIs onto cloud API Gateway products where the code is predominantly written and hosted in FaaS.

* This is designed to pass "Function" Components into it.  Consider it like a use-case harness which can accept "Function" Components.

* This should be designed so that you can keep your REST API definition in a single configuration file that accepts outputs from other projects containing the "Functions" and more.  Breaking up larger REST APIs enabling teams to work on each piece autonomously is a requirement.  Fetching outputs from other projects should be done exclusively through remote storage first, not locally.  Something alike this...

```yaml
name: functions

getUser:
  component: @serverless/function
  inputs:
    code: uses.get
    runtime: nodejs12

outputs:
  getUser: getUser
```

```yaml
name: api

api:
  component: @serverless/rest-api
  inputs:
    routes:
      /users:
        get: 
          function: ${remote:usersGet}
```
        

### Queue

This is a Component for message queues that are connecting predominantly to FaaS.

### Website

This is a Component for provisioning a static website.

* This uses the "Code" Component behind the scenes to build code.
