### ISSUE TITLE
YAML can't parse array of objects

### ISSUE THREAD

**Issue by eahefnawy** [serverless/components#452]
with config like this:

```yml
myApig:
  component: ../../
  inputs:
    name: ${name}
    endpoints:
      - path: /posts
        method: get
        function: ${comp:myFunction}
        authorizer: ${comp:auth}
      - path: /posts
        method: post
        function: ${comp:myFunction}
        authorizer: ${comp:auth}
      - path: /posts
        method: put
        function: ${comp:myFunction}
        authorizer: ${comp:auth}
      - path: /posts
        method: delete
        function: ${comp:myFunction}
        authorizer: ${comp:auth}

```

I need to add this hack in every component that requires it:

```js
    // todo quick fix for array of objects in yaml issue
    inputs.endpoints = Object.keys(inputs.endpoints).map((e) => inputs.endpoints[e])
```
