### ISSUE TITLE
Component: PubSub

### ISSUE THREAD

**Issue by eahefnawy** [serverless/components#453]
As part of the #449 epic, we need to create a cross provider higher level abstraction for PubSub. It should use the `aws-sns-topic` & `aws-sns-subscription` components to construct a new simpler PubSub component.

It should minimally look something like this:

```yml
myFunction:
    component: "@serverless/function"
    inputs:
        ...

PubSub:
    component: "@serverless/pub-sub"
    inputs:
        - source: topic-name # eventually this should support other providers and not specific to aws topics
          function: ${comp:myFunction}
        - ... # more PubSub pairings here
```
