### ISSUE TITLE
Component: aws-sqs

### ISSUE THREAD

**Issue by eahefnawy** [serverless/components#455]
```yml
sqsQueue:
  component: "@serverless/aws-sqs"
  inputs:
    name: queue-name
    ...
```

more info about the expected inputs could be found here:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#createQueue-property
