### ISSUE TITLE
Circular dependency with @serverless/api

### ISSUE THREAD

**Issue by Pavel910** [serverless/components#476]
# Description
This is the most basic configuration to reproduce the problem:

```yml
name: graphql-api

gateway:
  component: '@serverless/function'
  inputs:
    description: Apollo Server
    code: ./src
    handler: index.handler
    env:
      API_URL: ${api.url}
api:
  component: '@serverless/api'
  inputs:
    endpoints:
      - path: /api
        method: ANY
        function: ${gateway}
```
I need to inject the API Gateway output URL as an `env` variable for my lambda, as I need to know the absolute URL of the API from within the lambda itself.

Running `sls` results in the following error:
```
Pavels-Mac:repro paveldenisjuk$ sls

  error:
  Error: Your template has circular dependencies:
    1. api --> gateway
       gateway <-- api
    at validateGraph (/usr/local/lib/node_modules/serverless/node_modules/@serverless/template/utils.js:91:11)
    at createGraph (/usr/local/lib/node_modules/serverless/node_modules/@serverless/template/utils.js:250:3)
    at Template.default (/usr/local/lib/node_modules/serverless/node_modules/@serverless/template/serverless.js:38:19)

  2s › Template › Error: Your template has circular dependencies:
    1. api --> gateway
       gateway <-- api
```

## Additional data
```
sls --version
1.49.0 (Enterprise Plugin: 1.3.8, Platform SDK: 2.1.0)
```

I'm not sure if this is a bug or an intended behavior, but this is definitely a nice-to-have feature to avoid manually assigning the API URL after the initial project deploy.
