### ISSUE TITLE
Inputs coming through as an empty object

### ISSUE THREAD

**Issue by EwanValentine** [serverless/components#478]
# Description
Apologies if this is a silly issue, I'm trying to create a custom component, but my inputs are coming through as an empty object when I run `serverless --debug`, well... I say empty, there's a key of 'debug: true' and nothing else. 

Here's my component:

```javascript
'use strict';

const AWS = require('aws-sdk');
const { Component } = require('@serverless/core');
const sd = new AWS.ServiceDiscovery();

class CloudmapComponent extends Component {

  async default(inputs = {}) {
    console.log(inputs); // this outputs a blank object {} :(
    const { services } = inputs;

    this.state.name = 'CloudmapComponent';

    services.forEach(async (service) => {
      const params = {
        Name: service.name,
        NamespaceId: service.namespace,
        Description: service.description,
      };
      const { Id } = await sd.createService(params).promise();
      await Promise.all(service.instances.map((instance) => {
        const params = {
          Attributes: {
            type: 'function',
            arn: instance.function.arn,
            ...instance.config,
          },
          InstanceId: instance.name,
          ServiceId: Id,
        };
        return sd.registerInstance(params).promise();
      }));
    });
  }
}

module.exports = CloudmapComponent;
```

Here's my test serverless.yml file

```yaml
name: serverless-cloudmap-component

createUser:
  component: "@serverless/function"
  inputs:
    name: ${name}-create-user
    code: ./code
    handler: index.createUser

cloudmapComponent:
  component: ./
  inputs:
    services:
      - name: 'user-service'
        namespace: 'some-id'
        description: 'Some Service'
        instances:
          - name: 'create'
            function: ${createUser}
```

Running on serverless version `1.50.0`, on Mac OSX, node version `v8.11.3`.

Thanks in advance!
