### ISSUE TITLE
Question: possible to place component's serverless.js in a separate folder?

### ISSUE THREAD

**Issue by doitadrian** [serverless/components#482]
# Description
I have a very simple question, possibly a feature request. :)

This is the example from the docs:
```
name: my-serverless-website

website:
  component: @serverless/website
  inputs: # Inputs to pass into the component's default function
    code:
      src: ./src
```

Would it be possible to specify the actual folder in which the component (`serverless.js`) file is located? Eg.: 

```
name: my-serverless-website

website:
  component: @serverless/website/some-folder
  inputs: # Inputs to pass into the component's default function
    code:
      src: ./src
```

Maybe I should explain my use case. 

I want to publish an NPM module, which will contain all of the necessary business logic, and also a SLS component, so that consumers can easily deploy the module to the cloud. 

Thank you in advance and congrats on this awesome piece of software. 😊
