### ISSUE TITLE
Allow outputs masking

### ISSUE THREAD

**Issue by laardee** [serverless/components#494]
# Description

When deploying the outputs might contain secrets or sensitive stuff which should not be written to logs. For example, if there is some service which returns an access token after deployment and which is in the outputs for later use. Now that token will be exposed. It's not a big problem when you deploy with your own computer, but in the CI/CD pipelines are.

A generic solution could be something like

```yaml
myComponent:
  component: 'create-or-update-secret'
  mask:
    - hello.value
  inputs:
    secret-name: hello
```
output would be
```shell
myComponent:
  hello: *****
```

the `mask` parameter could be also an object

```yaml
myComponent:
  component: 'create-or-update-secret'
  mask:
    hello:
      value: true
  inputs:
    secret-name: hello
```

Or perhaps the object / arrray could include outputs

```yaml
myComponent:
  component: 'create-or-update-secret'
  mask:
    outputs:
      hello:
        value: true
  inputs:
    secret-name: hello
```
