### ISSUE TITLE
Custom, Branded URL Shortner Component with just API Gateway

### ISSUE THREAD

**Issue by eahefnawy** [serverless/components#496]
A great, simple and cheap use case for a component is a URL shortener that might just only require API Gateway proxies with a custom domain name.

```yml
shortner:
  component: @serverless/url-shortner
  inputs:
    domain: sls.io
    urls:

     # You could provide a custom path => sls.io/NewRelease
      - name: NewRelease
         url: https://serverless.com/blog/some-release-blog

     # or you could just have the component auto generate one for you => sls.io/qdjvbid
      - url: https://serverless.com/blog/some-thing-else
       
```

**outputs**
```
shortner:
  urls:
    - sls.io/NewRelease => https://serverless.com/blog/some-release-blog
    - sls.io/qdjvbid => https://serverless.com/blog/some-thing-else
```
