### ISSUE TITLE
Not deploy with domain

### ISSUE THREAD

**Issue by gleidsonh** [serverless/components#512]
`serverless.yml`
```
name: website

website:
  component: '@serverless/website'
  inputs:
    code:
      src: dist
      hook: npm run build
    domain: "https://my-domain.com"
```

I execute on terminal: **serverless**

I got this error: ValidationException: 2 validation errors detected: Value '[com, *.com]' at 'subjectAlternativeNames' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 253, Member must have length greater than or equal to 1, Member must satisfy regular expression pattern: ^(\*\.)?(((?!-)[A-Za-z0-9-]{0,62}[A-Za-z0-9])\.)+((?!-)[A-Za-z0-9-]{1,62}[A-Za-z0-9])$]; Value 'com' at 'domainName' failed to satisfy constraint: Member must satisfy regular expression pattern: ^(\*\.)?(((?!-)[A-Za-z0-9-]{0,62}[A-Za-z0-9])\.)+((?!-)[A-Za-z0-9-]{1,62}[A-Za-z0-9])$

I tried remove `https://`but not works. My domain has a hyphen.
