### ISSUE TITLE
Environment variable is not combined with extra string

### ISSUE THREAD

**Issue by imdatngo** [serverless/components#553]
## Description
The components' inputs are not parsed correctly when using environment variables with extra string, only the variable itself is assigned.

## Sample code

.env
```ini
DbTablePrefix="dev_"
```

serverless.yml
```yml
myTable:
  component: "@serverless/aws-dynamodb"
  inputs:
    name: ${env.DbTablePrefix}MyTableName
```

Deployment output:
```
$ serverless -v

  myTable: 
    name:   dev_
    arn:    arn:aws:dynamodb:ap-southeast-1:************:table/dev_
    region: ap-southeast-1
```

## Additional Data
Serverless version
```
Framework Core: 1.62.0
Plugin: 3.3.0
SDK: 2.3.0
Components Core: 1.1.2
Components CLI: 1.4.0
```
