### ISSUE TITLE
Website deploys, but not with 'serverless deploy'

### ISSUE THREAD

**Issue by MarkOnDuty** [serverless/components#563]
# Description
Using a very simple website application derived from the website template, I can deploy just fine with an `sls deploy --debug`, but it fails on an `sls deploy` (no debug). On failure, I get:

```
  error:
  Error: "component" input is required to run custom methods
    at Proxy.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/@serverless/template/utils.js:350:13)
    at Object.runComponents (/usr/local/lib/node_modules/serverless/node_modules/@serverless/cli/src/index.js:209:40)
```

All I've done is swap the website to one created using Nuxt.js, changed the hook to `npm run generate` to reflect the swap, and moved the web code into a subdirectory called frontend.

## Additional Data

The output of `serverless --version` from some directory that doesn't have a `serverless.yml` present:

```
Framework Core: 1.66.0
Plugin: 3.5.0
SDK: 2.3.0
Components: 2.22.3
```

My serverless.yml:
```
name: blah

blah:
  component: '@serverless/website'
  inputs:
    code:
      root: frontend
      src: dist
      hook: npm run generate
    domain: dev.blah.com
    region: ca-central-1
```
This is running on a Linux box, Ubuntu 16.04.6 LTS, with Node v11.11.0.

Interestingly, I accidentally did a `serverless create --template-url https://github.com/serverless/components/tree/master/templates/website` in the directory, and got the same error message as with a `sls deploy`.

Also, in trying to make sure this issue was complete, I did a `serverless --version`. Instead of doing as one might expect, that triggered a deploy, and the deploy worked fine. Doing just a plain `serverless` also works, but a `serverless deploy` still fails as described as above.
