### ISSUE TITLE
file exclude support proposal

### ISSUE THREAD

**Issue by hkbarton** [serverless/components#602]
Today, in component V2 we don't have a way to exclude files being upload, I think this is an important feature that customers can use this to avoid upload files/folders like credential files or maybe `node_modules` for node project. I talked this with @eahefnawy briefly yesterday, and currently, we have 2 proposals:

1. Add `exclude` support in `serverless.yml`, something looks like:
```
component: express
name: express-api-demo
stage: dev

inputs:
  src:
    hook: ls
    dist: ./src
    # the exclude supports glob syntax
    exclude: 
      - .env
      - 'node_modules/**'
      - '**/*.log'
```

2. Add excluding file support in ignore file like `.slsignore`, similar as `.gitignore`

I personally like 1, since it's close to the `inputs`, and I know what's being excluded from the inputs as well as the flexibility of having different exclude in sub repo `serverless.yml` since we support mono repo deployment now.

cc @eahefnawy @medikoo @ac360 @chrismcleod
