### ISSUE TITLE
How can I specify S3 bucket ? 

### ISSUE THREAD

**Issue by ahmad-crossplatform** [serverless/components#609]
# Description
Hello I am new to this ,  and I am using the website template to deploy to S3 . 
The problem is that in my build server (using github actions) it creates almost a different bucket on each deploy , how can I specify which bucket I want to deploy to ? 
## Additional Data

E.g. stack trace, version, operating system, ...

**Comment by eahefnawy** [comment]
@ahmad-crossplatform That doesn't sound right. how does your yaml look like?

**Comment by ahmad-crossplatform** [comment]
```
name: website

website:
  component: "@serverless/website"
  inputs:
    code:
      src: build
      hook: npm run build
    domain: beta.crossplatform.se
```

**Comment by eahefnawy** [comment]
ah yeah, you are still using V1 of the website component, which does not work in CI/CD. Please use V2 instead. It's a lot faster and more stable:
https://github.com/serverless-components/website

**Comment by ahmad-crossplatform** [comment]
@eahefnawy  thanks , but just to be clear , the difference between V1 and V2 is just the configuration right ? as long as i have the latest serverless cli .

**Comment by eahefnawy** [comment]
the implementation of each component is also different. So for a component that was deployed with v1 will likely break when deployed with v2.

If possible, I suggest that you remove your v1 component, change the config to be v2 compatible then deploy again. Hopefully, that would reduce the conflict risk

**Comment by ahmad-crossplatform** [comment]
@eahefnawy  when I tried the new config 

```
component: website # (required) name of the component. In that case, it's website.
name: crossplatform-website # (required) name of your website component instance.
org: serverlessinc # (optional) serverless dashboard org. default is the first org you created during signup.                   # (optional) serverless dashboard app. default is the same as the name property.
stage: dev # (optional) serverless dashboard stage. default is dev.

inputs:
  src: ./src # (optional) path to the source folder. default is a hello world html file.
  domain: beta.crossplatform.se # (optional) domain name. this could also be a subdomain.
  region: eu-north-1 # (optional) aws region to deploy to. default is us-east-1.
  bucketName: beta.crossplatform.se # (optional) aws bucket name. default is an auto generated name.
```

I got an error 

```

 Error: 401 - Your credentials do not have access to t
he Organization with the name of: serverlessinc.  Try logging into a different account.
```
while the old configuration worked fine . 
have i done something wrong ?
