### ISSUE TITLE
please update the readme

### ISSUE THREAD

**Issue by sambP** [serverless/components#615]
- ${env.x} and not ${env:x}
- --stage=x is not working, why is it still in the readme?

Perhaps there is much more... Currently it is very complicated to get started because of that.

**Comment by eahefnawy** [comment]
You may be running V1 of components. How does your yaml look like?

**Comment by sambP** [comment]
```
name: x

next:
  component: serverless-next.js
  inputs:
    bucketName: ${env.BUCKET_NAME}
    policy: "x"
  build:
    env:
      BASE_URL: ${env.BASE_URL}

```

    "serverless": "^1.53.0",
    "serverless-next.js": "^1.9.10",
    "@serverless/core": "^1.1.2",
    "@serverless/template": "^1.1.3",
