### ISSUE TITLE
'componentName' is required

### ISSUE THREAD

**Issue by zhangxu3486432** [serverless/components#630]
# Description

run

```
sls deploy --all
```

occur error

```
 Error: 'componentName' is required
    at validateAndFormat (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/platform-client-china/src/instance.js:115:11)
    at run (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/platform-client-china/src/instance.js:255:14)
    at Object.deploy (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/platform-client-china/src/instance.js:312:9)
    at ServerlessSDK.deploy (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/platform-client-china/src/index.js:397:27)
    at fn (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/components/src/cli/utils.js:592:36)
    at executeGraph (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/components/src/cli/utils.js:606:19)
    at executeGraph (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/components/src/cli/utils.js:615:10)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/components/src/cli/commands-cn/runAll.js:62:36)
    at async Object.module.exports (/Users/zhangxu/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/@serverless/components/src/cli/index.js:110:7)

0s › zhangxu › 'componentName' is required
```

## serverless.yml

```yaml
component: '@serverless/tencent-django'
name: ADreamBackend

org: ADream
app: ADreamAPP
stage: dev


inputs:
  region: ${env:REGION}
  zone: ${env:ZONE}
  functionName: ADreamFun
  djangoProjectName: backend
  code: ./
  functionConf:
    timeout: 10
    memorySize: 256
    environment:
      variables:
        DEBUG: true
        NAME: ${output:${stage}:${app}:ADreamPG.private.dbname}
        USER: ${output:${stage}:${app}:ADreamPG.private.user}
        PASSWORD: ${output:${stage}:${app}:ADreamPG.private.password}
        HOST: ${output:${stage}:${app}:ADreamPG.private.host}
        PORT: ${output:${stage}:${app}:ADreamPG.private.port}
    vpcConfig:
      subnetId: ${output:${stage}:${app}:ADreamVpc.vpcId}
      vpcId: ${output:${stage}:${app}:ADreamVpc.subnetId}
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
```

or

```yaml
DjangoTest:
  component: '@serverless/tencent-django'
  inputs:
    region: ap-guangzhou
    functionName: DjangoFunctionTest
    djangoProjectName: backend
    code: ./
    functionConf:
      timeout: 10
      memorySize: 256
      environment:
        variables:
          TEST: vale
      vpcConfig:
        subnetId: ''
        vpcId: ''
    apigatewayConf:
      protocols:
        - http
      environment: release
```

ps:

What's the difference between 
```yaml
component: '@serverless/tencent-django'
name: ADreamBackend

inputs:
....
```
 and 

```yaml
DjangoTest:
  component: '@serverless/tencent-django'
  inputs:
```

Thank you very much for reading my question.

**Comment by makutamoto** [comment]
@zhangxu3486432 
I have the same problem.
How did you manage to solve?

**Comment by SunnyDark** [comment]
Did you find a solution?

**Comment by dclaze** [comment]
Can we re-open this question or add a FAQ somewhere?

**Comment by geoffatsource** [comment]
same issue here

**Comment by gouroujo** [comment]
this issue should be reopen or did you find a solution @zhangxu3486432 ?

**Comment by zhangxu3486432** [comment]
it is my now yaml, work fine

[tencent-django](https://github.com/serverless-components/tencent-django)
[tencent-framework-components](https://github.com/serverless-components/tencent-framework-components)

```yaml
org: ${env:ORG}
app: ${env:APP}
stage: ${env:STAGE}

component: django
name: ${env:DJANGO_NAME}

inputs:
  region: ${env:REGION}
  zone: ${env:ZONE}
  functionName: ${name}-${stage}-${app}-${org}
  djangoProjectName: backend
  src: ./
  functionConf:
    timeout: 20
    memorySize: 256
    vpcConfig:
      vpcId: ${output:${stage}:${app}:${env:VPC_NAME}.vpcId}
      subnetId: ${output:${stage}:${app}:${env:VPC_NAME}.subnetId}
  apigatewayConf:
    isDisabled: true # 是否禁用自动创建 API 网关功能
    protocols:
      - https
    environment: ${env:APIGATEWAYENV}
    serviceTimeout: 20
```
