### ISSUE TITLE
Feature Proposal: support inputs for custom component method

### ISSUE THREAD

**Issue by hkbarton** [serverless/components#640]
Currently, we only support inputs for the `deploy` method on the component. We do support using `sls custom-method` to run any method in the component, but there is no way to pass in any inputs to those custom methods. I'm proposing adding a new section in `serverless.yml` to define the inputs for the custom method:

```
component: scf
name: demo
app: demoApp
stage: dev

inputs: # this is only for deploy
   src: ./src

actionInputs: # this section defines any inputs for arbitrary method in the component
  invoke: # suppose we have a method called invoke in scf component
    param1: "test1" # invoke method in scf component can read this parameter from inputs
    src: ./test.json # action inputs also supports uploading some files and getting those files in custom method
  test: 
    src: ./test-case.json
```

**Comment by eahefnawy** [comment]
Or maybe:

```yml
inputs:
  deploy:
    src: ./src

  invoke:
    test: abc
```

I feel like the structure is getting more and more verbose in both approaches though. I would love to keep the yaml file simple. @hkbarton what is the custom action you wanna pass inputs to?

**Comment by hkbarton** [comment]
@eahefnawy for a specific use case, I think the cloud function invoke is a useful one. so the user can use `sls invoke` to directly access and run a cloud function with some test input. This is useful for test cloud function without fire the real trigger event.

**Comment by medikoo** [comment]
> Or maybe:
> 
> ```yml
> inputs:
>   deploy:
>    src: ./src
> 
>  invoke:
>    test: abc
> ```

I think it cannot work reliably together with maintaining support for current way. As otherwise what would be the logic to detect if user configured inputs for different commands or just for deploy command. There seems no clean and safe way to resolve that.

--- 

Maybe better would be to introduce something as:

```yaml
commandInputs:
  deploy:
    src: ./src

  invoke:
    test: abc
```

And at same time maintain support for:

```yaml
inputs: # deploy only inputs
  src: ./src
```
