### ISSUE TITLE
Warning: You are using a Beta version of Serverless Component.

### ISSUE THREAD

**Issue by zhangxu3486432** [serverless/components#717]
# Description

Warning: You are using a Beta version of Serverless Component. Use the official version for more features.

```yaml
name: adream
stage: prod

REGION: ap-beijing
ZONE: ap-beijing-3
```

I've set the `stage` to `prod`, why warning still on?
