### ISSUE TITLE
zipping src directory should support target dir

### ISSUE THREAD

**Issue by yugasun** [serverless/components#736]
# Description

When user config `src`, all sub directory in `src` will be zipped, but the parent directory will be discarded.

 For example:

```yaml
inputs:
  src: ./node_modules
```

All sub director/files will be compressed into zip file, but parent path `node_modules` will be discarded.

Sometimes, user want to keep it, so I suggest to support `targetDir` config for this requirement, when user config like below:

```yaml
inputs:
  src: ./node_modules
  targetDir: /node_modules
```

All sub dir/files of `node_modules` will be compressed into `node_modules` path.

**Comment by hkbarton** [comment]
is `targetDir` a path? so in this demo, the code will be zipped into `node_modules` folder in root? @yugasun

**Comment by hkbarton** [comment]
if I understand correctly the `targetDir` should always start with `/`? it's like path prefix for target file structure.

**Comment by yugasun** [comment]
> node_modules

Yeah, `targetDir` is a path.

**Comment by yugasun** [comment]
@hkbarton Yeah, just a  `prefix` for target file structure.

**Comment by hkbarton** [comment]
shouldn't the config like this I think:

```yaml
inputs:
   src:
      src:  ./node_modules
      targetDir: /node_modules
```
