### ISSUE TITLE
Publishing/Installation re-orders YAML and inserts a blank line

### ISSUE THREAD

**Issue by ac360** [serverless/components#759]
This is evident within the `fullstack-app` example.

Here is the `serverless.yml` BEFORE publishing via `publish`:

```yaml
component: express
app: fullstack
name: api

inputs:
  ...
```

Here is the `serverless.yml` AFTER installation via `init`:

```yaml
app: fullstack-app
component: express

name: api

inputs:
  ...
```

I think we should do this:

- [ ] Always use this order on installation:

```
app:
component:
name:
```

- [ ] Ensure line breaks look like this, only:
```
app:
component:
name:

inputs:
  ...
```
