### ISSUE TITLE
how to best integrate webpack/typescript into serverless components

### ISSUE THREAD

**Issue by mwawrusch** [serverless/components#833]
I am using webpack and typescript with aws-lambda component, as shown below.
This is a bit inefficient to replicate for each lambda, and also it does not integrate into serverless dev and serverless. 

What would be a possible solution, besides creating a new component on top of aws-lambda, to automatically trigger a rebuild before serverless deploys? 

webpack.config.js
```

const path = require('path');

module.exports = {
  mode: "production",
  entry: './src/handler.ts',
  target: 'node',
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
    ],
  },
  resolve: {
    extensions: [ '.tsx', '.ts', '.js' ],
  },
  output: {
    libraryTarget: "commonjs",
    filename: 'handler.js',
    path: path.resolve(__dirname, 'dist'),
  },
  externals: {
    'aws-sdk': 'aws-sdk'
  },
};


```

tsconfig.json
```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "sourceMap": false,
    "noImplicitAny": true,
    "jsx": "react",
    "allowJs": true,
    "allowSyntheticDefaultImports" : true,
    "esModuleInterop" : true,

    "module": "es2015",
    "target": "esnext",
    "strict": false,
    "types": ["node"],
    "resolveJsonModule": true,
    "moduleResolution": "node",
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitReturns": false,
    "noFallthroughCasesInSwitch": true,
    "lib": ["ES2020.Promise"]
  }
}
```

**Comment by mwawrusch** [comment]
Also, how would I go about configuring source map for certain stages (dev)?

**Comment by mwawrusch** [comment]
So @Pavel910  posted this https://github.com/serverless-heaven/serverless-webpack/issues/525#issuecomment-522321229

Basically, all we need (if we don't want to create our own component) is a hook parameter in aws-lambda component.

**Comment by mwawrusch** [comment]
Got this working by using the hook parameter.

Here is some sample code for others:
```
org: rojiio
app: aws-backend-issuer
component: aws-lambda
name: issuer-inbound-kyc-status-changed
stage: dev

inputs:
  src:
    src: ./
    dist: ./dist
    hook: npx webpack
  handler: handler.handler
  env:
    STAGE: ${stage}
  description: Handles changes in kyc status.

  roleName: ${output:role-lambda.name}
  # memory: 512                    # (optional) lambda memory size.
  # timeout: 10                    # (optional) lambda timeout.

```
tsconfig.json
```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "sourceMap": false,
    "noImplicitAny": true,
    "jsx": "react",
    "allowJs": true,
    "allowSyntheticDefaultImports" : true,
    "esModuleInterop" : true,

    "module": "es2015",
    "target": "esnext",
    "strict": false,
    "types": ["node"],
    "resolveJsonModule": true,
    "moduleResolution": "node",
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitReturns": false,
    "noFallthroughCasesInSwitch": true,
    "lib": ["ES2020.Promise"]
  }
}
```
webpack.config.js
```
const path = require('path');

module.exports = {
  mode: "production",
  entry: './src/handler.ts',
  target: 'node',
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
      {
        test: /\.(graphql|gql)$/,
        exclude: /node_modules/,
        loader: 'graphql-tag/loader',
      },
    ],
  },
  resolve: {
    extensions: [ '.tsx', '.ts', '.js' ],
  },
  output: {
    libraryTarget: "commonjs",
    filename: 'handler.js',
    path: path.resolve(__dirname, 'dist'),
  },
  externals: {
    'aws-sdk': 'aws-sdk',
    'react': 'react',
  }
};

```
