### ISSUE TITLE
The example for website component does not work as expected

### ISSUE THREAD

**Issue by bugb** [serverless/components#849]
# Description
OS: Linux

Serverless version: Components version 2.34.9

I am trying to use `website` component following this instructions here: https://github.com/serverless/components#simplicity

Steps:

- Run `npx serverless init react-starter`

- Run `cd react-starter`

- Update config for `serverless.yml` file

Here is my `serverless.yml` file:

```
app: react-starter
name: react-starter
component: website

inputs:
  src:
    src: ./src
    hook: npm run build
    dist: ./dist
    env:
      # environment variables to pass to the website build environment
      REACT_APP_API_URL: https://google.com
  domain: 
    mydomain.com
```

After few minutes from running `serverless`, I can access my cloudront domain name to access it

![image](https://user-images.githubusercontent.com/9280412/101676747-29717300-3a8e-11eb-9f4f-fcd6667f321b.png)

But I can not use my own domain (for example: `mydomain.com`) to access it

## Additional Data
- I use domain from Amazon

- Here is the image of this problem when accessing from browser when typing `mydomain.com`:

![image](https://user-images.githubusercontent.com/9280412/101676017-275ae480-3a8d-11eb-8d3a-45712216044d.png)
