### ISSUE TITLE
Issue with serverless components backend

### ISSUE THREAD

**Issue by mwawrusch** [serverless/components#854]
Sent this via multiple channels but haven't heard back within 7 days from anyone, and it is blocking us from going to production... 

There is a bug somewhere in the components backend service that prevents the correct resolving of named entities when more than one stage is used.

For example, I define an AWS role that is used by a lambda, it is created both in dev and prod, however, the Lamba fails to publish to prod because it can't find the role. It does find it for dev though.

**Comment by eahefnawy** [comment]
Can you provide some steps to try to reproduce this? How does your yaml file look like?

**Comment by eahefnawy** [comment]
are you referencing the role via output variables like this?

```yml
inputs:
  role: ${output:myRole.name}
```

**Comment by mwawrusch** [comment]
Thanks for getting back to me.
Role definition:
```
component: aws-iam-role             # (required) name of the component. In that case, it's aws-iam-role.
org: rojiio
app: aws-backend-issuer
name: role-lambda
stage: dev

inputs:
  name: ${stage}-${app}-${name}
  service: lambda.amazonaws.com     # (optional) service that assumes this role. default is lambda.amazonaws.com.
  policy:                           # (optional) inline policy statement, or managed policy arn. default is the admin arn.
    - Effect: Allow
      Action:
        - sts:AssumeRole
      Resource: '*'
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: '*'
    - Effect: Allow
      Action:
        - ssm:GetParameters
      Resource: '*' # TODO: [ROJI-388] aws-backend-issuer - Permissions need to be finetuned here

    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource: '*' # TODO: [ROJI-477]  aws-backend-issuer - Permissions need to be finetuned here

    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: '*' # TODO: [ROJI-487] aws-backend-issuer Permissions need to be finetuned here

      
      ```
      
  Lambda definition:
  
  ```
  org: rojiio
app: aws-backend-issuer
component: aws-lambda
name: issuer-inbound-kyc-status-changed
stage: dev

inputs:
  src:
    src: ./
    dist: ./dist
    hook: npx webpack
  handler: handler.handler
  env:
    STAGE: ${stage}
  description: Handles changes in kyc status.

  roleName: ${output:role-lambda.name}
  # memory: 512                    # (optional) lambda memory size.
  # timeout: 10                    # (optional) lambda timeout.
```

Also, we use separate AWS accounts for prod and dev, using the env mechanism described in the docs
