### ISSUE TITLE
Serverless component not deploying

### ISSUE THREAD

**Issue by danim47c** [serverless/components#877]
I am trying to deploy some components but I get the same error every time I execute `severless` command:

```
TypeError: Cannot redefine property: router
    at Function.defineProperty (<anonymous>)
    at Function.defaultConfiguration (/home/danim47c/.serverless/components/registry/npm/express@4.17.1/node_modules/express/lib/application.js:122:10)
    at Function.init (/home/danim47c/.serverless/components/registry/npm/express@4.17.1/node_modules/express/lib/application.js:62:8)
    at Template.load (/home/danim47c/advtechdev/towing-app-serverless/node_modules/@serverless/core/src/Component.js:116:34)
    at async fn (/home/danim47c/advtechdev/towing-app-serverless/node_modules/@serverless/template/utils.js:272:25)
    at async Promise.all (index 0)
    at async executeGraph (/home/danim47c/advtechdev/towing-app-serverless/node_modules/@serverless/template/utils.js:294:3)
    at async Template.default (/home/danim47c/advtechdev/towing-app-serverless/node_modules/@serverless/template/serverless.js:67:38)
    at async Object.runComponents `(/home/danim47c/advtechdev/towing-app-serverless/node_modules/@serverless/cli/src/index.js:220:17)
```

```yml
website:
  component: "@sls-next/serverless-component"

api:
  component: express
  inputs:
    src:
      src: ./api
      hook: npm run build
      dist: build
```
