### ISSUE TITLE
How do I deploy to different subdomains based on stage?

### ISSUE THREAD

**Issue by nectarcode** [serverless/components#909]
# Description

I'd like to deploy to dev.api.mydomain.com if the stage is dev, and api.mydomain.com if the stage is prod.

I tried changing the domain manually when I change the stage, but I get the error:

`Changing the domain from api.mydomain.com to dev.mydomain.com will remove your infrastructure.  Please remove it manually, change the domain, then re-deploy.`

I don't want to remove my infrastructure at api.mydomain.com, I'd like to deploy the same code to two different subdomains. Is this achievable or am I missing something?

## Additional Data

serverless.yml

```
component: express@1.7.1
name: mydomain-api
org: mydomain
stage: dev

inputs:
  src: ./
  domain: api.mydomain.com
```

**Comment by nectarcode** [comment]
If i try deploying to api.mydomain.com with the production stage, I get the following error.

`The domain api.mydomain.com is already in use by another API`

So as of right now it seems I can only deploy dev stage, and only to a single subdomain.

**Comment by mwawrusch** [comment]
You define it in your .env and .env.prod file, then use a reference like this in your serverless.yml file:

```

inputs:
  src: ./
  region: us-east-1
  domain: ${env:GRAPHQL_DOMAIN}
 ```
