### ISSUE TITLE
Setting custom parameters for a component in serverless.yml

### ISSUE THREAD

**Issue by tomyates** [serverless/components#933]
I'm struggling to set custom parameters in serverless.yml and access them in my express component.

I've tried:

```
app: sa-api
component: express
name: sa-api

inputs:
  src: ./

custom:
  TWITTER_ACCESS_TOKEN: 'testToken'
```

and:

```
app: sa-api
component: express
name: sa-api

inputs:
  src: ./

TWITTER_ACCESS_TOKEN: 'testToken'
```

But the parameter isn't listed when I `console.log(process.env)`

I'm intending on using parameters I have setup in the Serverless Dashboard, ( `${param:<key>}` ), once I get this working.

Thanks.

**Comment by tomyates** [comment]
For some reason, I did't spot this in plain sight in the documentation. The following works:

```
app: sa-api
component: express
name: sa-api

inputs:
  src: ./
  env:
    SPOTIFY_CLIENT_SECRET: ${param:spotifyClientSecret}
    SPOTIFY_CLIENT_ID: ${param:spotifyClientId}
  
```
